# Generated by Django 5.2.4 on 2025-08-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_editorelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorelement',
            name='position_x',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='editorelement',
            name='position_y',
            field=models.FloatField(default=0.5),
        ),
    ]
