# Generated by Django 5.2.4 on 2025-08-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_editorelement_position_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorelement',
            name='height',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='editorelement',
            name='width',
            field=models.FloatField(default=0.2),
        ),
    ]
